### PR TITLE
Update accelerate arg passthrourgh for tensorboard logging to reflect logging_dir deprecation.

### PR DESCRIPTION
**Pull request by jganitkevitch**
accelerate moved from `logging_dir` to use ProjectConfiguration, updating examples to reflect.

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thank you very much for these changes
This looks great to me, can you just merge your current branch with upstream main? https://github.com/lvwerra/trl/pull/441 there was a small regression on the CI tests

**Comment by jganitkevitch** [comment]
Done!

**Review by younesbelkada — APPROVED** [review]
Thanks for this! Great work!
cc @vwxyzjn would be great if you can have a quick second look 🙏 
Thanks!

**Comment by younesbelkada** [comment]
Merging as we're planning to do a patch release today!

**Pull request merged**
