### PR TITLE
fix style, typos, license

### PR DESCRIPTION
**Pull request by natolambert**
Was just skimming the code to learn, fixed stuff as I saw it.

### CODE REVIEW

**Comment by lvwerra** [comment]
Thanks for the fixes @natolambert! Did you run the linter on the examples? I see there are a lot of changes there. If we want to do that I think we should update the CI and Makefile too so they stay clean in the future. No strong opinion tbh.

**Comment by natolambert** [comment]
Yep I did, I can add them to `make` or revert, preference @lvwerra ?
My linter was just complaining when I went through so I did it once.

**Comment by lvwerra** [comment]
I think adding is good, then we have consistently formatted examples :)

**Comment by natolambert** [comment]
Okay @lvwerra -- made the updates and merged with main, lets make sure it passes again then feel free to merge.

**Pull request merged**
