### PR TITLE
Give a key to the wandb PPOConfig config entry

### PR DESCRIPTION
**Pull request by JulesGM**
There is a lot of stuff with very generic keys in the `PPOConfig` dict, and the user may have logged a `wandb` config dict elsewhere. I know I had that problem. To counter that, I pass the PPOConfig dict in a dict under the key `trl_ppo_trainer_config`, to prevent collisions & be very clear.

### CODE REVIEW

**Comment by JulesGM** [comment]
Not sure what to do with the test that's failing. 

Anyways. @lvwerra would be curious to know what you think about this PR. Thanks.

**Review by younesbelkada — APPROVED** [review]
This looks good to me and your explanation sounds correct
Let's wait to see what @lvwerra will say

**Review by lvwerra — APPROVED** [review]

**Comment by lvwerra** [comment]
Sounds good! Let's wait for the CI fix and rebase before merging :)

**Comment by JulesGM** [comment]
cool! I merged with the main branch.

**Review by younesbelkada — APPROVED** [review]
Thanks again for your great work on this!

**Comment by tobigue** [comment]
Hey, this commit breaks logging with tensorboard, as the torch tensorboard SummaryWriter can not handle nested dicts. (`ValueError: value should be one of int, float, str, bool, or torch.Tensor`)

Complete stack trace:

```
Cell In[25], line 1
----> 1 ppo_trainer = PPOTrainer(config, ppo_model, ref_model, tokenizer)

File ~/env/src/trl/trl/trainer/ppo_trainer.py:186, in PPOTrainer.__init__(self, config, model, ref_model, tokenizer, dataset, optimizer, data_collator, num_shared_layers, lr_scheduler)
    180 # Step 1: Initialize Accelerator
    181 self.accelerator = Accelerator(
    182     log_with=config.log_with,
    183     gradient_accumulation_steps=config.gradient_accumulation_steps,
    184     **config.accelerator_kwargs,
    185 )
--> 186 self.accelerator.init_trackers(
    187     config.tracker_project_name,
    188     config=dict(trl_ppo_trainer_config=config.to_dict()),
    189     init_kwargs=config.tracker_kwargs,
    190 )
    192 self.model = model
    193 self.is_encoder_decoder = hasattr(self.model, "is_encoder_decoder")

File ~/env/lib/python3.8/site-packages/accelerate/accelerator.py:548, in Accelerator.on_main_process.<locals>._inner(*args, **kwargs)
    547 def _inner(*args, **kwargs):
--> 548     return PartialState().on_main_process(function)(*args, **kwargs)

File ~/env/lib/python3.8/site-packages/accelerate/accelerator.py:2037, in Accelerator.init_trackers(self, project_name, config, init_kwargs)
   2035 if config is not None:
   2036     for tracker in self.trackers:
-> 2037         tracker.store_init_configuration(config)

File ~/env/lib/python3.8/site-packages/accelerate/tracking.py:83, in on_main_process.<locals>.execute_on_main_process(self, *args, **kwargs)
     80 @wraps(function)
     81 def execute_on_main_process(self, *args, **kwargs):
     82     if getattr(self, "main_process_only", False):
---> 83         return PartialState().on_main_process(function)(self, *args, **kwargs)
     84     else:
     85         return function(self, *args, **kwargs)

File ~/env/lib/python3.8/site-packages/accelerate/tracking.py:211, in TensorBoardTracker.store_init_configuration(self, values)
    200 @on_main_process
    201 def store_init_configuration(self, values: dict):
    202     """
    203     Logs `values` as hyperparameters for the run. Should be run at the beginning of your experiment. Stores the
    204     hyperparameters in a yaml file for future use.
   (...)
    209             `str`, `float`, `int`, or `None`.
    210     """
--> 211     self.writer.add_hparams(values, metric_dict={})
    212     self.writer.flush()
    213     project_run_name = time.time()

File ~/env/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py:336, in SummaryWriter.add_hparams(self, hparam_dict, metric_dict, hparam_domain_discrete, run_name)
    334 if type(hparam_dict) is not dict or type(metric_dict) is not dict:
    335     raise TypeError("hparam_dict and metric_dict should be dictionary.")
--> 336 exp, ssi, sei = hparams(hparam_dict, metric_dict, hparam_domain_discrete)
    338 if not run_name:
    339     run_name = str(time.time())

File ~/env/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py:229, in hparams(hparam_dict, metric_dict, hparam_domain_discrete)
    227         hps.append(HParamInfo(name=k, type=DataType.Value("DATA_TYPE_FLOAT64")))
    228         continue
--> 229     raise ValueError(
    230         "value should be one of int, float, str, bool, or torch.Tensor"
    231     )
    233 content = HParamsPluginData(session_start_info=ssi, version=PLUGIN_DATA_VERSION)
    234 smd = SummaryMetadata(
    235     plugin_data=SummaryMetadata.PluginData(
    236         plugin_name=PLUGIN_NAME, content=content.SerializeToString()
    237     )
    238 )

ValueError: value should be one of int, float, str, bool, or torch.Tensor
```

**Comment by JulesGM** [comment]
Ok I'll modify this to add a prefix to the keys instead. will send in a
few hours.

**Comment by younesbelkada** [comment]
Hi @JulesGM !
Thanks again for the PR, as I consider that the issue was a bit urgent, I made the PR myself 🤗 https://github.com/lvwerra/trl/pull/330 
@tobigue this should fix your issue

**Pull request merged**
