### PR TITLE
feat(ci): enable `pip` cache

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
This PR sets the `cache` and `cache-dependency-path` argument of `actions/setup-python` to enable pip caching.

### CODE REVIEW

**Comment by lvwerra** [comment]
Hi @SauravMaheshkar, thanks for opening a PR! If I understand it correctly this integration hashes the requirements/setup files to cache dependencies. In that case we would be quite blind to breaking changes from new versions of a library, right?

**Comment by SauravMaheshkar** [comment]
@lvwerra as far as I understand, the action reuses cache if the files listed under the `cache-dependency-path` haven't been changed for while. If the files have been recently changed then it updates the cache. So we should not be blind to breaking changes from new versions.

**Comment by lvwerra** [comment]
I think the issue is that we don't change the files in question often so it is possible that there are breaking changes that we don't notice because we never updated the cached files. Is there an option to set a cache lifetime?

**Comment by SauravMaheshkar** [comment]
AFAIK there isn't a option to set cache lifetime however we can use the `cache-hit` flag to check if a cache hit has occurred. [Source](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#cache-hit)

**Comment by lvwerra** [comment]
Hi @SauravMaheshkar, not sure I follow how the cache-hit would help. I would like to at least clear the cache once every 1-2 days since libraries might be updated that the we won't install due to caching.

**Comment by SauravMaheshkar** [comment]
Hey @lvwerra thanks for the feedback, you do make an interesting case. Upon searching around for a bit, we can create another workflow [similar to the one in the Github Docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries) which can clear all the caches every `n` days.

**Comment by SauravMaheshkar** [comment]
Do you want me to work on that as well in this PR ?

**Comment by lvwerra** [comment]
Hi @SauravMaheshkar, yes, if we can delete the cache every 1-2 days adding caching would be a good feature.

**Comment by SauravMaheshkar** [comment]
@lvwerra I added a proposal for a workflow in e19ce2072fa0dc17c4dc8b60d009ed08f9d7d8f4

**Comment by lvwerra** [comment]
Awesome work @SauravMaheshkar , that looks great to me! What do you think @younesbelkada ?

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for this awesome feature!
I am totally ok for this PR, I just have few (basic) questions
- Where the duration of the cache refreshing mechanism (you stated each 1 or 2 days) can be changed on the file you have added?
- Why the changes on `tests.yml` are needed? It seems to be applied only on python 3.8, do we need to change it as well for other python versions?
Thanks a lot!

**Comment by lvwerra** [comment]
For the first question `- cron: "0 0 * * *"` specifies refresh at midnight (see [here](https://crontab.guru)). Also curious about the second one!

**Comment by younesbelkada** [comment]
> For the first question - cron: "0 0 * * *" specifies refresh at midnight (see [here](https://crontab.guru/)).
Awesome thank you!

**Comment by SauravMaheshkar** [comment]
> Thanks a lot for this awesome feature! I am totally ok for this PR, I just have few (basic) questions
> 
> * Where the duration of the cache refreshing mechanism (you stated each 1 or 2 days) can be changed on the file you have added?
> * Why the changes on `tests.yml` are needed? It seems to be applied only on python 3.8, do we need to change it as well for other python versions?
>   Thanks a lot!

We can run the tests on other python versions as well. The changes proposed by this PR is independent of the python version. We can test for more python versions as well.

**Comment by SauravMaheshkar** [comment]
> Hi @SauravMaheshkar just to double check: it seems like the cache is only a pip download cache and the libraries still need to be installed (which takes a significant amount of time). Is this expected?

Yes it's just a download cache AFAIK

**Pull request merged**
