### PR TITLE
PPO config __init__ is bloated 

### PR DESCRIPTION
**Pull request by GauravVirmani**
### What does this PR do?

Fixes: https://github.com/lvwerra/trl/issues/233

Moving `total_ppo_epochs`, `forward_batch_size` and `log_with` to post init method and let the dataclass automatically assign the other member variables.

cc @edbeeching @lvwerra

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Awesome work, that looks great to me. Thanks a mile for fixing

**Comment by edbeeching** [comment]
Would it be worthwhile removing the long args description and using fields + metadata?
For example:  `log_with: Optional[str] = field(default=None, metadata={"help": "use 'wandb' to log with wandb"})`

**Comment by younesbelkada** [comment]
Hi @GauravVirmani ,
Can you run the styling checks?
``bash
make style && make quality
```

**Comment by younesbelkada** [comment]
Hi @GauravVirmani 
I think there is a mismatch between our `black` versions, mine is:
```bash
>>> import black
>>> black.__version__
'23.1.0'
```
Can you please double check?

**Comment by GauravVirmani** [comment]
Hey @younesbelkada 

My version is same:

image

Is there a way to run these checks in my local machine?  Let me try running the styling checks again.

**Comment by younesbelkada** [comment]
Hmm in my experience you just need to run `make style && make quality`. Otherwise I can do it for you

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for all your work on this!

**Comment by lvwerra** [comment]
Thanks @GauravVirmani for fixing the merged PR!

**Review by lvwerra — APPROVED** [review]

**Pull request merged**
