### PR TITLE
StackLLaMA: fix supervised finetuning and reward model training

### PR DESCRIPTION
**Pull request by mnoukhov**
for supervised finetuning
- removed tokenizer hacks since they are no longer necessary with the updated `llamatokenizer`
- black + isort

for reward modeling
- added `tokenizer_name` so it can be separately specified from model
- again removed old llama tokenizer hacks
- added `eval_first_step` option to add an eval loop after the first step to make nicer graphs
- black + isort

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks for your hardwork @mnoukhov ! 
I have the same comments as here: https://github.com/lvwerra/trl/pull/398#pullrequestreview-1457294425 
If you run the styling checks we should be all good!

**Comment by mnoukhov** [comment]
Ran the checks and added the configs to my workspace config for the future :)

**Review by younesbelkada — APPROVED** [review]
Thanks a lot!

**Review by lvwerra — APPROVED** [review]
Thanks a lot for updating!

**Pull request merged**
