### PR TITLE
Update sft_trainer.py

### PR DESCRIPTION
**Pull request by plaggy**
Looks like a minor bug in _prepare_non_packed_dataloader. Worked for me after this change.

### CODE REVIEW

**Review by lvwerra — APPROVED** [review]
Thanks for the fix, that looks good to me. I let @younesbelkada confirm.

**Review by younesbelkada — COMMENTED** [review]
Hi @plaggy 
Thanks for the PR, can you elaborate on the issue you were getting?
I think the current condition is correct, one should use the formatting function only if `formatting_func` is not `None` and `dataset_text_field` is `None`, the formatting function should take care of getting the proper text fields

**Comment by plaggy** [comment]
Hi @younesbelkada, thank you for looking into it! Totally my bad, didn't look properly into the behaviour without the text field specified. Sorry for the false alarm :)

**Comment by younesbelkada** [comment]
No problem ! @plaggy thanks again !

**Pull request closed without merging**
